spring:
  thymeleaf:
    cache: false
    #prefix: classpath:/templates/layuicms/
    prefix: classpath:/templates/page/
    suffix: .html
    encoding: UTF-8
    content-type: text/html
  #mvc:
  # view:
  #   prefix: /WEB-INF/jsp/
  #   suffix: .jsp
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?characterEncoding=utf-8
    username: root
    password: root
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1 from dual
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    filters: stat, wall, log4j
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  http:
    multipart:
      max-request-size: 2048Mb
      max-file-size: 1024Mb
  #缓存接口
  redis:
    host: 127.0.0.1
    port: 6379
    pool:
      max-idle: 20
      min-idle: 1
      max-active: 20
      max-wait: 60000
    database: 0

# 日志
debug: true
logging:
  level:
    com.xugb.controller: 'off'
    root: debug


# mybatis
mybatis:
  type-aliases-package: com.xugb.entity
  mapper-locations: classpath:mapper/*.xml

# pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  # Mapper
mapper:
  mapper: com.xugb.mapper.mapper
  not-empty: false
  identity: MYSQL



